### ISSUE TITLE
Agent crashes when parsing proxy

### ISSUE THREAD

**Issue by woanware** [MythicAgents/Athena#3]
Created Athena payload, ran on the host, crashed with the following error:

```
Unhandled exception. System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Athena.Config.HTTP..ctor(String uuid) in /tmp/tmptxjoypu_00572087-df47-4fbe-9fd6-f8221c348623/Athena/Config/MythicConfig.cs:line 71
   at Athena.Config.MythicConfig..ctor() in /tmp/tmptxjoypu_00572087-df47-4fbe-9fd6-f8221c348623/Athena/Config/MythicConfig.cs:line 30
   at Athena.MythicClient..ctor() in /tmp/tmptxjoypu_00572087-df47-4fbe-9fd6-f8221c348623/Athena/MythicClient.cs:line 21
   at Athena.Program.Main(String[] args) in /tmp/tmptxjoypu_00572087-df47-4fbe-9fd6-f8221c348623/Athena/Program.cs:line 21
```

Note that the agent was not configured with **any** proxy values, so in theory they should have been blank values.

I created a fork, commented out the offending code, and pulled in my modified agent, and it then works without crashing. 

The changes can be seen here:
https://github.com/woanware/Athena/commit/cade6aef61eaf8ca689c73ac9972aeb917599554

**Comment by checkymander** [comment]
What are you putting in for the proxy value? I could theoretically just check to see what parts are missing and add them if needed. The URI value *should* look like http(s)://<ip or fqdn> and then the rest of it should be parsed from the mythic agent

**Comment by woanware** [comment]
If you need any extra info then let me know
