### ISSUE TITLE
Race Condition in Upload command

### ISSUE THREAD

**Issue by checkymander** [MythicAgents/Athena#64]
When uploading files with a fast enough sleep time sometimes, the handle won't be closed in time before the next chunk arrives to the agent:

```
Failed to process message.System.IO.IOException: The process cannot access the file 'C:\Users\myuser\Desktop\Athena.exe' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at Agent.Plugin. (Byte[], String)
```

Likely cause is chunks arriving quicker than the handle is able to be closed by the OS, need to add some locking or waiting to fix

**Comment by checkymander** [comment]
Fixed in latest release
